config/routes.rb
OpenStreetMap::Application.routes.draw do
  # API
  match "api/capabilities" => "api#capabilities", :via => :get
  match "api/0.6/capabilities" => "api#capabilities", :via => :get
  match "api/0.6/permissions" => "api#permissions", :via => :get

  match "api/0.6/changeset/create" => "changeset#create", :via => :put
  match "api/0.6/changeset/:id/upload" => "changeset#upload", :via => :post, :id => /\d+/
  match "api/0.6/changeset/:id/download" => "changeset#download", :via => :get, :as => :changeset_download, :id => /\d+/
  match "api/0.6/changeset/:id/expand_bbox" => "changeset#expand_bbox", :via => :post, :id => /\d+/
  match "api/0.6/changeset/:id" => "changeset#read", :via => :get, :as => :changeset_read, :id => /\d+/
  match "api/0.6/changeset/:id/subscribe" => "changeset#subscribe", :via => :post, :as => :changeset_subscribe, :id => /\d+/
  match "api/0.6/changeset/:id/unsubscribe" => "changeset#unsubscribe", :via => :post, :as => :changeset_unsubscribe, :id => /\d+/
  match "api/0.6/changeset/:id" => "changeset#update", :via => :put, :id => /\d+/
  match "api/0.6/changeset/:id/close" => "changeset#close", :via => :put, :id => /\d+/
  match "api/0.6/changesets" => "changeset#query", :via => :get
  post "api/0.6/changeset/:id/comment" => "changeset#comment", :as => :changeset_comment, :id => /\d+/
  post "api/0.6/changeset/comment/:id/hide" => "changeset#hide_comment", :as => :changeset_comment_hide, :id => /\d+/
  post "api/0.6/changeset/comment/:id/unhide" => "changeset#unhide_comment", :as => :changeset_comment_unhide, :id => /\d+/

  match "api/0.6/node/create" => "node#create", :via => :put
  match "api/0.6/node/:id/ways" => "way#ways_for_node", :via => :get, :id => /\d+/
  match "api/0.6/node/:id/relations" => "relation#relations_for_node", :via => :get, :id => /\d+/
  match "api/0.6/node/:id/history" => "old_node#history", :via => :get, :id => /\d+/
  match "api/0.6/node/:id/:version/redact" => "old_node#redact", :via => :post, :version => /\d+/, :id => /\d+/
  match "api/0.6/node/:id/:version" => "old_node#version", :via => :get, :id => /\d+/, :version => /\d+/
  match "api/0.6/node/:id" => "node#read", :via => :get, :id => /\d+/
  match "api/0.6/node/:id" => "node#update", :via => :put, :id => /\d+/
  match "api/0.6/node/:id" => "node#delete", :via => :delete, :id => /\d+/
  match "api/0.6/nodes" => "node#nodes", :via => :get

  match "api/0.6/way/create" => "way#create", :via => :put
  match "api/0.6/way/:id/history" => "old_way#history", :via => :get, :id => /\d+/
  match "api/0.6/way/:id/full" => "way#full", :via => :get, :id => /\d+/
  match "api/0.6/way/:id/relations" => "relation#relations_for_way", :via => :get, :id => /\d+/
  match "api/0.6/way/:id/:version/redact" => "old_way#redact", :via => :post, :version => /\d+/, :id => /\d+/
  match "api/0.6/way/:id/:version" => "old_way#version", :via => :get, :id => /\d+/, :version => /\d+/
  match "api/0.6/way/:id" => "way#read", :via => :get, :id => /\d+/
  match "api/0.6/way/:id" => "way#update", :via => :put, :id => /\d+/
  match "api/0.6/way/:id" => "way#delete", :via => :delete, :id => /\d+/
  match "api/0.6/ways" => "way#ways", :via => :get

  match "api/0.6/relation/create" => "relation#create", :via => :put
  match "api/0.6/relation/:id/relations" => "relation#relations_for_relation", :via => :get, :id => /\d+/
  match "api/0.6/relation/:id/history" => "old_relation#history", :via => :get, :id => /\d+/
  match "api/0.6/relation/:id/full" => "relation#full", :via => :get, :id => /\d+/
  match "api/0.6/relation/:id/:version/redact" => "old_relation#redact", :via => :post, :version => /\d+/, :id => /\d+/
  match "api/0.6/relation/:id/:version" => "old_relation#version", :via => :get, :id => /\d+/, :version => /\d+/
  match "api/0.6/relation/:id" => "relation#read", :via => :get, :id => /\d+/
  match "api/0.6/relation/:id" => "relation#update", :via => :put, :id => /\d+/
  match "api/0.6/relation/:id" => "relation#delete", :via => :delete, :id => /\d+/
  match "api/0.6/relations" => "relation#relations", :via => :get

  match "api/0.6/map" => "api#map", :via => :get

  match "api/0.6/trackpoints" => "api#trackpoints", :via => :get

  match "api/0.6/changes" => "api#changes", :via => :get

  match "api/0.6/search" => "search#search_all", :via => :get
  match "api/0.6/ways/search" => "search#search_ways", :via => :get
  match "api/0.6/relations/search" => "search#search_relations", :via => :get
  match "api/0.6/nodes/search" => "search#search_nodes", :via => :get

  match "api/0.6/user/:id" => "user#api_read", :via => :get, :id => /\d+/
  match "api/0.6/user/details" => "user#api_details", :via => :get
  match "api/0.6/user/gpx_files" => "user#api_gpx_files", :via => :get

  match "api/0.6/user/preferences" => "user_preference#read", :via => :get
  match "api/0.6/user/preferences/:preference_key" => "user_preference#read_one", :via => :get
  match "api/0.6/user/preferences" => "user_preference#update", :via => :put
  match "api/0.6/user/preferences/:preference_key" => "user_preference#update_one", :via => :put
  match "api/0.6/user/preferences/:preference_key" => "user_preference#delete_one", :via => :delete

  match "api/0.6/gpx/create" => "trace#api_create", :via => :post
  match "api/0.6/gpx/:id" => "trace#api_read", :via => :get, :id => /\d+/
  match "api/0.6/gpx/:id" => "trace#api_update", :via => :put, :id => /\d+/
  match "api/0.6/gpx/:id" => "trace#api_delete", :via => :delete, :id => /\d+/
  match "api/0.6/gpx/:id/details" => "trace#api_read", :via => :get, :id => /\d+/
  match "api/0.6/gpx/:id/data" => "trace#api_data", :via => :get

  # AMF (ActionScript) API
  match "api/0.6/amf/read" => "amf#amf_read", :via => :post
  match "api/0.6/amf/write" => "amf#amf_write", :via => :post
  match "api/0.6/swf/trackpoints" => "swf#trackpoints", :via => :get

  # Map notes API
  scope "api/0.6" do
    resources :notes, :except => [:new, :edit, :update], :constraints => { :id => /\d+/ }, :defaults => { :format => "xml" } do
      collection do
        get "search"
        get "feed", :defaults => { :format => "rss" }
      end

      member do
        post "comment"
        post "close"
        post "reopen"
      end
    end

    match "notes/addPOIexec" => "notes#create", :via => :post
    match "notes/closePOIexec" => "notes#close", :via => :post
    match "notes/editPOIexec" => "notes#comment", :via => :post
    match "notes/getGPX" => "notes#index", :via => :get, :format => "gpx"
    match "notes/getRSSfeed" => "notes#feed", :via => :get, :format => "rss"
  end

  # Data browsing
  match "/way/:id" => "browse#way", :via => :get, :id => /\d+/, :as => :way
  match "/way/:id/history" => "browse#way_history", :via => :get, :id => /\d+/
  match "/node/:id" => "browse#node", :via => :get, :id => /\d+/, :as => :node
  match "/node/:id/history" => "browse#node_history", :via => :get, :id => /\d+/
  match "/relation/:id" => "browse#relation", :via => :get, :id => /\d+/, :as => :relation
  match "/relation/:id/history" => "browse#relation_history", :via => :get, :id => /\d+/
  match "/changeset/:id" => "browse#changeset", :via => :get, :as => :changeset, :id => /\d+/
  match "/changeset/:id/comments/feed" => "changeset#comments_feed", :via => :get, :as => :changeset_comments_feed, :id => /\d*/, :defaults => { :format => "rss" }
  match "/note/:id" => "browse#note", :via => :get, :id => /\d+/, :as => "browse_note"
  match "/note/new" => "browse#new_note", :via => :get
  match "/user/:display_name/history" => "changeset#list", :via => :get
  match "/user/:display_name/history/feed" => "changeset#feed", :via => :get, :defaults => { :format => :atom }
  match "/user/:display_name/notes" => "notes#mine", :via => :get
  match "/history/friends" => "changeset#list", :via => :get, :friends => true, :as => "friend_changesets", :defaults => { :format => :html }
  match "/history/nearby" => "changeset#list", :via => :get, :nearby => true, :as => "nearby_changesets", :defaults => { :format => :html }

  get "/browse/way/:id",                :to => redirect(:path => "/way/%{id}")
  get "/browse/way/:id/history",        :to => redirect(:path => "/way/%{id}/history")
  get "/browse/node/:id",               :to => redirect(:path => "/node/%{id}")
  get "/browse/node/:id/history",       :to => redirect(:path => "/node/%{id}/history")
  get "/browse/relation/:id",           :to => redirect(:path => "/relation/%{id}")
  get "/browse/relation/:id/history",   :to => redirect(:path => "/relation/%{id}/history")
  get "/browse/changeset/:id",          :to => redirect(:path => "/changeset/%{id}")
  get "/browse/note/:id",               :to => redirect(:path => "/note/%{id}")
  get "/user/:display_name/edits",      :to => redirect(:path => "/user/%{display_name}/history")
  get "/user/:display_name/edits/feed", :to => redirect(:path => "/user/%{display_name}/history/feed")
  get "/browse/friends",                :to => redirect(:path => "/history/friends")
  get "/browse/nearby",                 :to => redirect(:path => "/history/nearby")
  get "/browse/changesets/feed",        :to => redirect(:path => "/history/feed")
  get "/browse/changesets",             :to => redirect(:path => "/history")
  get "/browse",                        :to => redirect(:path => "/history")

  # web site
  root :to => "site#index", :via => [:get, :post]
  match "/edit" => "site#edit", :via => :get, :as => :edit
  match "/copyright/:copyright_locale" => "site#copyright", :via => :get
  match "/copyright" => "site#copyright", :via => :get
  match "/welcome" => "site#welcome", :via => :get, :as => :welcome
  match "/fixthemap" => "site#fixthemap", :via => :get, :as => :fixthemap
  match "/help" => "site#help", :via => :get, :as => :help
  match "/about" => "site#about", :via => :get, :as => :about
  match "/history" => "changeset#list", :via => :get
  match "/history/feed" => "changeset#feed", :via => :get, :defaults => { :format => :atom }

app/helpers/changeset_helper.rb
module ChangesetHelper
  def changeset_user_link(changeset)
    if changeset.user.status == "deleted"
      t("user.no_such_user.deleted")
    elsif changeset.user.data_public?
      link_to(changeset.user.display_name, user_path(changeset.user.display_name))
    else
      t("browse.anonymous")
    end
  end

  def changeset_details(changeset)
    if changeset.closed_at > Time.now
      action = :created
      time = distance_of_time_in_words_to_now(changeset.created_at)
      title = l(changeset.created_at)
    else
      action = :closed
      time = distance_of_time_in_words_to_now(changeset.closed_at)
      title = "#{t('browse.created')}: #{l(changeset.created_at)}&#10;#{t('browse.closed')}: #{l(changeset.closed_at)}".html_safe
    end

    if params.key?(:display_name)
      t "browse.#{action}_html",
        :time => time,
        :title => title
    else
      t "browse.#{action}_by_html",
        :time => time,
        :title => title,
        :user => changeset_user_link(changeset)
    end
  end

  def changeset_list_title(params, user)
    if params[:friends] && user
      t "changeset.list.title_friend"
    elsif params[:nearby] && user
      t "changeset.list.title_nearby"
    elsif params[:display_name]
      t "changeset.list.title_user", :user => params[:display_name]
    else
      t "changeset.list.title"
    end
  end
end

app/views/changeset/_changeset.html.erb
<%
   changeset_data = {:id => changeset.id}

   if changeset.has_valid_bbox?
     bbox = changeset.bbox.to_unscaled
     changeset_data[:bbox] = {
       :minlon => bbox.min_lon,
       :minlat => bbox.min_lat,
       :maxlon => bbox.max_lon,
       :maxlat => bbox.max_lat
     }
   end
%>

<%= content_tag "li", :id => "changeset_#{changeset.id}", :data => {:changeset => changeset_data} do %>
  <h4>
    <a class="changeset_id" href="<%= changeset_path(changeset.id) %>">
      <%= changeset.tags['comment'].to_s.presence || t('browse.no_comment') %>
    </a>
  </h4>
  <div class="comments comments-<%= changeset.comments.length %>">
    <%= changeset.comments.length %>
    <span class="icon note grey"></span>
  </div>
  <div class="details">
    <%= changeset_details(changeset) %>
    &middot;
    #<%= changeset.id %>
  </div>
<% end %>

app/views/changeset/_comment.html.erb
<h2><%= t "changeset.rss.comment", :author => comment.author.display_name, 
  :changeset_id => comment.changeset.id.to_s %></h2>
<div class="changeset-comment" style="margin-top: 5px">
  <div class="changeset-comment-description" style="font-size: smaller; color: #999999"><%= t "changeset.rss.commented_at_by_html", :when => friendly_date(comment.created_at), :user => comment.author.display_name %></div>
  <div class="changeset-comment-text"><%= comment.body %></div>
</div>

app/views/changeset/history.html.erb
<% content_for :auto_discovery_link_tag do -%>
  <% unless params[:friends] or params[:nearby] -%>
    <%= auto_discovery_link_tag :atom, @params.merge(:max_id => nil, :xhr => nil, :action => :feed) %>
  <% end -%>
<% end -%>

<%
   set_title(changeset_list_title(params, current_user))
   if params[:display_name]
     @heading = t('changeset.list.title_user', :user => link_to(params[:display_name], :controller => "user", :action => "view", :display_name => params[:display_name])).html_safe
   else
     @heading = @title
   end
%>

<h2>
  <a class="geolink" href="<%= root_path %>"><span class="icon close"></span></a>
  <%= @heading %>
</h2>

<div class="changesets">
  <%= image_tag "searching.gif", :class => "loader" %>
</div>

app/views/changeset/list.html.erb
<% if @edits.present? %>
  <ol class="changesets">
    <%= render :partial => 'changeset', :collection => @edits %>
  </ol>
<% if @edits.size == 20 -%>
  <div class="changeset_more">
    <%= link_to t('changeset.list.load_more'), url_for(@params.merge(:max_id => @edits.last.id - 1)), :class => "button load_more" %>
    <%= image_tag "searching.gif", :class => "loader", :style => "display: none;" %>
  </div>
<% end -%>
<% elsif params[:bbox] %>
  <div class="inner22"><%= t(params[:max_id] ? 'changeset.list.no_more_area' : 'changeset.list.empty_area') %></div>
<% elsif params[:display_name] %>
  <div class="inner22"><%= t(params[:max_id] ? 'changeset.list.no_more_user' : 'changeset.list.empty_user') %></div>
<% else %>
  <div class="inner22"><%= t(params[:max_id] ? 'changeset.list.no_more' : 'changeset.list.empty') %></div>
<% end %>

app/views/changeset/timeout.html.erb
<p><%= t'changeset.timeout.sorry' %></p>